[window]

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
size = 17.0
offset.x=-2
